package com.tpxl.client;


import com.tpxl.protocol.packets.FriendListPacket;
import com.tpxl.protocol.packets.SearchFriendsResponsePacket;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.net.ssl.SSLServerSocket;
import javax.net.ssl.SSLServerSocketFactory;
import javax.net.ssl.SSLSocket;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TP
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private final int STATE_LOGIN = 0;
    private final int STATE_REGISTER = 1;
    
    public int LOGIN_STATE = STATE_LOGIN;
    Thread t;
    Client client;
    
    ArrayList<Thread> P2Pthreads;
    
    public MainFrame() {
        initComponents();
        activateLoginPanel();
        client = new Client(this);
        t = new Thread(client);
        t.start();
        P2Pthreads = new ArrayList<Thread>();
        while(client.serverConnection == null)
        	{
        		System.out.println("connection = null");
        		try {
					Thread.sleep(50);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        	}
        client.serverConnection.sendHelloPacket();
    }

    public void logout()
    {
        t.stop();
        client = new Client(this);
        t = new Thread(client);
        t.start();
        while(client.serverConnection == null) System.out.println("connection = null");
        client.serverConnection.sendHelloPacket();
        activateLoginPanel();
        setTitle("");
        for(int i=0; i<P2Pthreads.size(); i++)
        	P2Pthreads.get(i).stop();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusLabel = new javax.swing.JLabel();
        dummyPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activeFriendsList = new javax.swing.JList();
        loginPanel = new javax.swing.JPanel();
        usernameTextfield = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        friendsSearchPanel = new javax.swing.JPanel();
        searchTextbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        searchEndCheckbox = new javax.swing.JCheckBox();
        searchBeginCheckbox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchFriendsList = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuMessenger = new javax.swing.JMenu();
        MenuMessengerChangeNickname = new javax.swing.JMenuItem();
        MenuMessengerSignOut = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuMessengerExit = new javax.swing.JMenuItem();
        MenuContacts = new javax.swing.JMenu();
        MenuContactsAddFriend = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuContactsRemoveFriend = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuHelpAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StatusLabel.setText("Hello!");
        getContentPane().add(StatusLabel, java.awt.BorderLayout.PAGE_END);

        dummyPanel.setLayout(new java.awt.CardLayout());

        mainPanel.setPreferredSize(new java.awt.Dimension(400, 246));

        activeFriendsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        activeFriendsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activeFriendsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(activeFriendsList);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        dummyPanel.add(mainPanel, "card2");

        usernameTextfield.setText("Username");
        usernameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextfieldActionPerformed(evt);
            }
        });
        usernameTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });

        loginButton.setText("Sign in");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerLabel.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        registerLabel.setText("Don't have an account? Click here.");
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register(evt);
            }
        });

        passwordTextField.setText("12984578");
        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        passwordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        passwordTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usernameTextfield)
                        .addComponent(passwordTextField))
                    .addComponent(loginButton))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(registerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        dummyPanel.add(loginPanel, "card3");

        searchTextbox.setText("Name");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        searchEndCheckbox.setText("Ending in");

        searchBeginCheckbox.setText("Begining in");
        searchBeginCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBeginCheckboxActionPerformed(evt);
            }
        });

        searchFriendsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFriendsListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(searchFriendsList);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout friendsSearchPanelLayout = new javax.swing.GroupLayout(friendsSearchPanel);
        friendsSearchPanel.setLayout(friendsSearchPanelLayout);
        friendsSearchPanelLayout.setHorizontalGroup(
            friendsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendsSearchPanelLayout.createSequentialGroup()
                .addComponent(searchTextbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchEndCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBeginCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addGroup(friendsSearchPanelLayout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(friendsSearchPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        friendsSearchPanelLayout.setVerticalGroup(
            friendsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendsSearchPanelLayout.createSequentialGroup()
                .addGroup(friendsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(searchEndCheckbox)
                    .addComponent(searchBeginCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );

        dummyPanel.add(friendsSearchPanel, "card4");

        getContentPane().add(dummyPanel, java.awt.BorderLayout.CENTER);

        MenuMessenger.setText("Messenger");

        MenuMessengerChangeNickname.setText("Change nickname");
        MenuMessengerChangeNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMessengerChangeNicknameActionPerformed(evt);
            }
        });
        MenuMessenger.add(MenuMessengerChangeNickname);

        MenuMessengerSignOut.setText("Sign out");
        MenuMessengerSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMessengerSignOutActionPerformed(evt);
            }
        });
        MenuMessenger.add(MenuMessengerSignOut);
        MenuMessenger.add(jSeparator1);

        MenuMessengerExit.setText("Exit");
        MenuMessengerExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMessengerExitActionPerformed(evt);
            }
        });
        MenuMessenger.add(MenuMessengerExit);

        jMenuBar1.add(MenuMessenger);

        MenuContacts.setText("Contacts");

        MenuContactsAddFriend.setText("Add");
        MenuContactsAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuContactsAddFriendActionPerformed(evt);
            }
        });
        MenuContacts.add(MenuContactsAddFriend);
        MenuContacts.add(jSeparator2);

        MenuContactsRemoveFriend.setText("Remove");
        MenuContactsRemoveFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuContactsRemoveFriendActionPerformed(evt);
            }
        });
        MenuContacts.add(MenuContactsRemoveFriend);

        jMenuBar1.add(MenuContacts);

        MenuHelp.setText("Help");

        MenuHelpAbout.setText("About");
        MenuHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpAboutActionPerformed(evt);
            }
        });
        MenuHelp.add(MenuHelpAbout);

        jMenuBar1.add(MenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMessengerSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMessengerSignOutActionPerformed
        logout();
    }//GEN-LAST:event_MenuMessengerSignOutActionPerformed

    private void MenuMessengerExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMessengerExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuMessengerExitActionPerformed

    private void MenuContactsAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContactsAddFriendActionPerformed
        activateFriendsSearchPanel();      // TODO add your handling code here:
    }//GEN-LAST:event_MenuContactsAddFriendActionPerformed

    private void MenuHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpAboutActionPerformed
        JOptionPane.showMessageDialog(this, "Made by Jure Kolenko", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MenuHelpAboutActionPerformed

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        if(passwordTextField.getText().equals("12984578"))
        passwordTextField.setText("");
    }//GEN-LAST:event_PasswordFocusGained

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed

    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void register(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register
        if(LOGIN_STATE == STATE_LOGIN)
        {
            LOGIN_STATE = STATE_REGISTER;
            registerLabel.setText("Already have an account? Click here.");
            loginButton.setText("Register");
        }else if(LOGIN_STATE == STATE_REGISTER)
        {
            LOGIN_STATE = STATE_LOGIN;
            registerLabel.setText("Don't have an account? Click here.");
            loginButton.setText("Sign in");
        }
    }//GEN-LAST:event_register

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(LOGIN_STATE == STATE_LOGIN) client.serverConnection.sendLoginPacket(usernameTextfield.getText(), passwordTextField.getText());
        else if(LOGIN_STATE == STATE_REGISTER) client.serverConnection.sendRegisterPacket(usernameTextfield.getText(), passwordTextField.getText());
        loginButton.setEnabled(false);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        if(usernameTextfield.getText().equals(""))
            usernameTextfield.setText("Username");
    }//GEN-LAST:event_UsernameFocusLost

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        if(usernameTextfield.getText().equals("Username"))
            usernameTextfield.setText("");
    }//GEN-LAST:event_UsernameFocusGained

    private void usernameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextfieldActionPerformed

    }//GEN-LAST:event_usernameTextfieldActionPerformed

    private void searchBeginCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBeginCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBeginCheckboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        client.serverConnection.sendSearchFriendsPacket((searchBeginCheckbox.isSelected()?"":"%") + searchTextbox.getText() + (searchEndCheckbox.isSelected()?"":"%"));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchFriendsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFriendsListMouseClicked
        if(evt.getClickCount() >= 2 && searchFriendsList.locationToIndex(evt.getPoint()) != -1)
        {
            int response = JOptionPane.showConfirmDialog(this, "Add " + searchFriendsList.getModel().getElementAt(searchFriendsList.getSelectedIndex()) + " to friends list?", "Friend add!", JOptionPane.OK_CANCEL_OPTION);
            SearchFriendsResponsePacket sfrp = client.serverConnection.friendResponses.get(searchFriendsList.locationToIndex(evt.getPoint()));
            client.serverConnection.sendFriendAddPacket(sfrp.getName(), sfrp.getID());
            StatusLabel.setText("Added " + sfrp.getName() + "!");
        }
    }//GEN-LAST:event_searchFriendsListMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        activateMainPanel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MenuContactsRemoveFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContactsRemoveFriendActionPerformed
        if(activeFriendsList.getSelectedIndex() != -1)
        {
            int response = JOptionPane.showConfirmDialog(this, "Delete " + activeFriendsList.getModel().getElementAt(activeFriendsList.getSelectedIndex()) + " from friends list?", "Friend remove!", JOptionPane.OK_CANCEL_OPTION);
            if(response == JOptionPane.OK_OPTION)
            {
                client.serverConnection.SendFriendRemovePacket(activeFriendsList.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_MenuContactsRemoveFriendActionPerformed

    private void MenuMessengerChangeNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMessengerChangeNicknameActionPerformed
        String s = JOptionPane.showInputDialog("Input your new nickname");
        if(s != null)
            client.serverConnection.sendChangeNicknamePacket(s);
    }//GEN-LAST:event_MenuMessengerChangeNicknameActionPerformed

    private void activeFriendsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeFriendsListMouseClicked
        if(evt.getClickCount() >= 2)
        {
            try {
            	File file = new File(client.serverConnection.publicKeyFile);
            	DataInputStream in = new DataInputStream(new FileInputStream(file));
    			byte[] data = new byte[(int) file.length()];
    			in.readFully(data);
    			
    			System.out.println("KEY FILE LENGTH SERVER" + data.length);
    			
                int index = activeFriendsList.getSelectedIndex();
                FriendListPacket flp = client.serverConnection.friendsByID.get(client.serverConnection.friends.get(index));
                client.serverConnection.sendConnectionStartRequestPacket(flp.getName(), flp.getID(), data);
                
                SSLServerSocketFactory sslssf = Client.getSecureServerSocketFactory(new FileInputStream(client.serverConnection.privateKeyFile));
                SSLServerSocket sslss = (SSLServerSocket)sslssf.createServerSocket(client.clientPort);
                SSLSocket sock = (SSLSocket)sslss.accept();
                Thread t = new Thread(new ClientToClientConnectionHandler(sock, client.serverConnection.username, flp.getName() + " " + flp.getNickname()));
                t.start();
                P2Pthreads.add(t);
            }catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_activeFriendsListMouseClicked

    private void passwordTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            loginButtonActionPerformed(null);
        }
    }//GEN-LAST:event_passwordTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public javax.swing.JLabel getStatusLabel()
    {
        return StatusLabel;
    }
    
    public javax.swing.JButton getLoginButton()
    {
        return loginButton;
    }
    
    public javax.swing.JTextField getUsernameTextfield()
    {
        return usernameTextfield;
    }
    
    
    public javax.swing.JPasswordField getPasswordTextfield()
    {
        return passwordTextField;
    }
    
    public void activateLoginPanel()
    {
        loginPanel.setVisible(true);
        mainPanel.setVisible(false);
        friendsSearchPanel.setVisible(false);
        
        ((CardLayout)dummyPanel.getLayout()).show(dummyPanel, "loginPanel");        
        MenuMessengerSignOut.setVisible(false);
        MenuMessengerChangeNickname.setVisible(false);
        MenuContacts.setVisible(false);
    }
    
    public void activateMainPanel()
    {
        loginPanel.setVisible(false);
        mainPanel.setVisible(true);
        friendsSearchPanel.setVisible(false);
        
        ((CardLayout)dummyPanel.getLayout()).show(dummyPanel, "mainPanel"); 
        
        MenuMessengerSignOut.setVisible(true);
        MenuMessengerChangeNickname.setVisible(true);
        MenuContacts.setVisible(true);
    }
    
    public void activateFriendsSearchPanel()
    {
        loginPanel.setVisible(false);
        mainPanel.setVisible(false);
        friendsSearchPanel.setVisible(true);
        
        ((CardLayout)dummyPanel.getLayout()).show(dummyPanel, "friendsSearchPanel"); 
        
        MenuMessengerSignOut.setVisible(true);
        MenuMessengerChangeNickname.setVisible(true);
        MenuContacts.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuContacts;
    private javax.swing.JMenuItem MenuContactsAddFriend;
    private javax.swing.JMenuItem MenuContactsRemoveFriend;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenuItem MenuHelpAbout;
    private javax.swing.JMenu MenuMessenger;
    private javax.swing.JMenuItem MenuMessengerChangeNickname;
    private javax.swing.JMenuItem MenuMessengerExit;
    private javax.swing.JMenuItem MenuMessengerSignOut;
    private javax.swing.JLabel StatusLabel;
    public javax.swing.JList activeFriendsList;
    private javax.swing.JPanel dummyPanel;
    private javax.swing.JPanel friendsSearchPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JCheckBox searchBeginCheckbox;
    private javax.swing.JCheckBox searchEndCheckbox;
    public javax.swing.JList searchFriendsList;
    private javax.swing.JTextField searchTextbox;
    private javax.swing.JTextField usernameTextfield;
    // End of variables declaration//GEN-END:variables
}
